# Generated by Django 5.0.7 on 2024-09-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_usersettings_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
