# Generated by Django 5.0.7 on 2024-08-31 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('nome_cliente', models.CharField(max_length=200)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('totale', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='prodotti/')),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('allergeni', models.ManyToManyField(blank=True, to='ordini.allergene')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='ordini.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('prezzo_totale', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementi', to='ordini.ordine')),
                ('prodotto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordini.prodotto')),
            ],
        ),
    ]
