# Generated by Django 5.0.7 on 2024-08-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='immagine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
