# Generated by Django 5.0.7 on 2024-09-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0002_alter_prodotto_immagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='n_ombrellone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordine',
            name='slot_delivery',
            field=models.TimeField(null=True),
        ),
    ]
