# Generated by Django 5.0.7 on 2024-09-03 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0004_alter_ordine_n_ombrellone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='email_cliente',
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='nome_cliente',
        ),
        migrations.AddField(
            model_name='ordine',
            name='utente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to=settings.AUTH_USER_MODEL),
        ),
    ]
