# Generated by Django 5.0.7 on 2024-09-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0006_remove_ordine_totale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='utente',
        ),
        migrations.AddField(
            model_name='ordine',
            name='cognome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='note',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
